function loadGlobalData(){
    var PIXI_globalData = {
        "BGA": {
            "URL": "",
            "width": 1920,
            "height": 1080,
            "BGColor": "FFFFFF",
            "screenScale":1
        },
        "inputA": {
            "motionJson": "",
            "spritesImageMode":1,
			"stillImageName":"",
            "spritesJson": "",
            "spritesImage": "",
            "anchor":0.5,
            "blendMode":"NORMAL",
            "adjust":{"speed":1,
                      "frameSpeed":1,
                      "spritesSize":1,
                      "spritesSizeRandom":0,
                      "spritesRotation":0,
                      "spritesRotationRandom":0,
                      "spritesFrameOffset":5,
                      "spritesTrans":1,
                      "spritesBlur":0},
            "stageDescriptJsonFile":"",
            "stageDescriptJsonData":"",
            "stage":{"stage_01":[{"position":{"x":0,"y":0}},
                                  {"scale":1},
                                  {"rotation":0},
                                  {"blendMode":0}]}
        },
        "inputB": {
            "motionJson": "",
            "spritesImageMode":1,
			"stillImageName":"",
            "spritesJson": "",
            "spritesImage": "",
            "anchor":0.5,
            "blendMode":"NORMAL",
            "adjust":{"speed":1,
                      "frameSpeed":1,
                      "spritesSize":1,
                      "spritesSizeRandom":0,
                      "spritesRotation":0,
                      "spritesRotationRandom":0,
                      "spritesFrameOffset":5,
                      "spritesBlur":0},
            "stageDescriptJsonFile":"",
            "stageDescriptJsonData":"",
            "stage":{"stage_01":[{"position":{"x":0,"y":0}},
                                  {"scale":1},
                                  {"rotation":0},
                                  {"blendMode":0}]}
        },
        "inputC": {
            "motionJson": "",
            "spritesImageMode":1,
			"stillImageName":"",
            "spritesJson": "",
            "spritesImage": "",
            "anchor":0.5,
            "blendMode":"NORMAL",
            "adjust":{"speed":1,
                      "frameSpeed":1,
                      "spritesSize":1,
                      "spritesSizeRandom":0,
                      "spritesRotation":0,
                      "spritesRotationRandom":0,
                      "spritesFrameOffset":5,
                      "spritesBlur":0},
            "stageDescriptJsonFile":"",
            "stageDescriptJsonData":"",
            "stage":{"stage_01":[{"position":{"x":0,"y":0}},
                                  {"scale":1},
                                  {"rotation":0},
                                  {"blendMode":0}]}
        },
        "inputD": {
            "motionJson": "",
            "spritesImageMode":1,
			"stillImageName":"",
            "spritesJson": "",
            "spritesImage": "",
            "anchor":0.5,
            "blendMode":"NORMAL",
            "adjust":{"speed":1,
                      "frameSpeed":1,
                      "spritesSize":1,
                      "spritesSizeRandom":0,
                      "spritesRotation":0,
                      "spritesRotationRandom":0,
                      "spritesFrameOffset":5,
                      "spritesBlur":0},
            "stageDescriptJsonFile":"",
            "stageDescriptJsonData":"",
            "stage":{"stage_01":[{"position":{"x":0,"y":0}},
                                  {"scale":1},
                                  {"rotation":0},
                                  {"blendMode":0}]}
        },
        "inputE": {
            "motionJson": "",
            "spritesImageMode":1,
			"stillImageName":"",
            "spritesJson": "",
            "spritesImage": "",
            "anchor":0.5,
            "blendMode":"NORMAL",
            "adjust":{"speed":1,
                      "frameSpeed":1,
                      "spritesSize":1,
                      "spritesSizeRandom":0,
                      "spritesRotation":0,
                      "spritesRotationRandom":0,
                      "spritesFrameOffset":5,
                      "spritesBlur":0},
            "stageDescriptJsonFile":"",
            "stageDescriptJsonData":"",
            "stage":{"stage_01":[{"position":{"x":0,"y":0}},
                                  {"scale":1},
                                  {"rotation":0},
                                  {"blendMode":0}]}
        }

    };

    return PIXI_globalData;
};
